export const NEW_TASK_REQUEST="NEW_TASK_REQUEST";
export const NEW_TASK_SUCCESS="NEW_TASK_SUCCESS";
export const NEW_TASK_FAIL="NEW_TASK_FAIL";

export const GET_TASK_REQUEST="GET_TASK_REQUEST";
export const GET_TASK_SUCCESS="GET_TASK_SUCCESS";
export const GET_TASK_FAIL="GET_TASK_FAIL";